default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: "v1.9.3" # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: template\.yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        name: Ruff (python)
  - repo: https://github.com/myint/docformatter
    rev: v1.7.6
    hooks:
      - id: docformatter
        args: ["--wrap-descriptions", "0"]
