AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a sample template for a serverless application that includes a
  Lambda function, an API Gateway REST API, and a DynamoDB table.

Globals:
  Api:
    TracingEnabled: True

Resources:
  MainApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  SimpleLayer:
    Type: AWS::Serverless::LayerVersion
    Description: Esta Layer almacenará las dependencias y el paquete de Python que representa a tu aplicación. Es necesario "empaquetar" tu código para que pueda ser utilizado por la función Lambda.
    Properties:
      ContentUri: dist/
      CompatibleRuntimes:
        - python3.13
  CheckStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Esta es una función de ejemplo que te permite revisar el stock de un producto en alamcen
      Runtime: python3.13
      CodeUri: handlers/
      Handler: api.check_stock
      Tracing: Active
      Layers:
        - !Ref SimpleLayer
      Events:
        GetStock:
          Type: Api
          Properties:
            Path: /store/{sku}
            Method: GET
            RestApiId: !Ref MainApi

  AddProductToCartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Esta es una función que te permite agregar un producto al carrito si hay existencias suficientes.
      Runtime: python3.13
      CodeUri: handlers/
      Handler: api.add_to_cart
      Tracing: Active
      Layers:
        - !Ref SimpleLayer
      Events:
        AddProduct:
          Type: Api
          Properties:
            Path: /cart
            Method: PUT
            RestApiId: !Ref MainApi
